name: "Neato"
description: "Neato"

inputs:
  tags:
    description: "The newline-separated tags to create"
    required: true

runs:
  using: "composite"

  steps:
    - uses: docker/build-push-action@v7
      with:
        tags: ${{ inputs.tags }}
