name: Continuous Integration

on:
  push:

jobs:
  step-on-toes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - parallel:
        - uses: ./.github/actions/neato
          with:
            tags: repro:alpha

        - uses: ./.github/actions/neato
          with:
            tags: repro:beta

        - uses: ./.github/actions/neato
          with:
            tags: repro:gamma
