on: [push, pull_request]

name: Continuous integration

jobs:
  secret_hierarchy:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: s390x
      - name: Cross test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target s390x-unknown-linux-gnu
