on: push

name: Continuous integration

jobs:
  library:
    environment: ci
    steps:
      - run: |-
        echo ${{ secrets.REPEATED_SECRET }} | wc
        echo ${{ secrets.SECRET_FROM_ENVIRONMENT }} | wc
        echo ${{ secrets.SECRET_FROM_REPO }} | wc
