name: Continuous integration

on:
  push:
  pull_request_target:
    branches:
    - main

jobs:
  anyone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run simple things
        run: echo 'I am safe'

  safe-secret:
    runs-on: ubuntu-latest

    environment: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run scary things
        run: echo "${{ secrets.REPEATED_SECRET }}"

      - name: Run scary things
        run: echo "${{ secrets.REPEATED_SECRET }}" | md5sum
