on: [pull_request]

name: Continuous integration

jobs:
  awesome:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     platforms: s390x
      - name: Cross test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target i686-unknown-linux-gnu
